### ISSUE TITLE
Some Questions about Parameters

### ISSUE THREAD

**Issue by JacobShenHdu** [Nate711/Doggo#33]
What does the parameter of “leg_direction” mean?Which leg does leg0, leg1, leg2, leg3 represent respectively?Thank you.

**Comment by CrazyAZ** [comment]
leg0 is the front left.  leg1 is the back left. leg2 is the back right. And leg3 is the front right.

leg_direction is a parameter related to which side of the robot the leg is on. The direction the legs on the right side rotate when the robot is walking forward is positive. The legs on the left side have to rotate the opposite direction relative to the body, so their leg_direction is negative.
