### ISSUE TITLE
Add state machine or task queue to better schedule events like jump or walking.

### ISSUE THREAD

**Issue by Nate711** [Nate711/Doggo#6]
We could use a task queue to keep track of events such as a jump command. In that case we'd append the jump behavior to the task queue and then wait for it to complete before going back to default behavior. Using a task queue instead of a state machine might be more extensible because instead of writing an additional switch statement for every new behavior, you would instead only write the behavior function and pass that a pointer to that function to the queue. Something like that anyways.

**Comment by CrazyAZ** [comment]
We now have a simple state machine implemented, but this could still be a useful feature to add in the future.
